Repository operate-first/operate-first.github.io-old, pull requests merged in 2020-12, with the labels that each got.

#139 modified deploy instructions
  README.md
Labels: approved, size/XS

#140 docs: Point to ODH Dashboard for MOC
  config/users.yaml
Labels: approved, size/XS

#149 Approvers
  OWNERS
Labels: approved, size/XS

#148 added entry to include flaky test detection notebook
  config/data-science.yaml
Labels: approved, size/XS

#147 let transformer-remark handle markdown
  gatsby-config.js
  gatsby-node.js
  package-lock.json
  package.json
  src/templates/Markdown.js
  src/templates/Markdown.scss
Labels: size/XXL

#151 upgraded dependencies
  package-lock.json
Labels: approved, size/XXL

#152 Add cloud price analysis content to operate first
  config/data-science.yaml
  gatsby-config.js
Labels: approved, size/S

#154 dont copy notebooks
  gatsby-config.js
Labels: approved, size/XS

#156 update data-science.yaml and Readme with new ocp-ci project links
  README.md
  config/data-science.yaml
Labels: approved, size/S

#158 auto link headers in markdown
  gatsby-config.js
  package-lock.json
  package.json
Labels: approved, size/M

#159 link /README.md and /
  gatsby-node.js
Labels: approved, size/S

#163 Add an article: Create a Jupyterhub image and deploy it on ODH.
  config/users.yaml
  gatsby-config.js
Labels: approved, size/S

#165 fix: MOC repo moved to GitHub
  gatsby-config.js
Labels: approved, size/XS
