Repository operate-first/operate-first.github.io-old, pull requests merged in 2020-11, with the labels that each got.

#61 Add MOC page
  .gitignore
  content-sources.yaml
  content/cd-toc.yaml
  content/moc-toc.yaml
  toc-sources.yaml
Labels: size/M

#66 modified moc repo url
  content-sources.yaml
Labels: size/XS

#68 Add content from data-science-workflow repo
  .gitignore
  content-sources.yaml
  content/dsw-toc.yaml
  toc-sources.yaml
Labels: size/S

#65 Modified command to output local branch
  package.json
  scripts/gh-pages-branch-fork.sh
Labels: approved, size/XS

#67 modified landing page content
  content/operate-first/index.md
Labels: approved, size/S

#69 Add remote source for categorical encoding blog
  .gitignore
  content-sources.yaml
  content/advanced-topics/categorical-encoding/approach.png
  content/advanced-topics/categorical-encoding/dataset.png
  content/advanced-topics/categorical-encoding/index.md
  content/advanced-topics/categorical-encoding/interpretation.png
  content/advanced-topics/categorical-encoding/results.png
  content/advanced-topics/categorical-encoding/rulepath.png
  content/toc.yaml
Labels: do-not-merge/needs-rebase, size/L

#79 updated project description for configuration file analysis project
  content/projects-overview/index.md
Labels: size/XS

#76 cleaned placeholder files
  content/advanced-topics/data-exploration/architecture.png
  content/advanced-topics/data-exploration/editor.png
  content/advanced-topics/data-exploration/hue-user-creation.png
  content/advanced-topics/data-exploration/index.md
  content/advanced-topics/data-exploration/new-database.png
  content/advanced-topics/data-exploration/query-results.png
  content/advanced-topics/data-exploration/routes.png
  content/advanced-topics/data-exploration/table-creation.png
  content/advanced-topics/data-exploration/tutorial.png
  content/data-science-projects/categorical-encoding/approach.png
  content/data-science-projects/categorical-encoding/dataset.png
  content/data-science-projects/categorical-encoding/index.md
  content/data-science-projects/categorical-encoding/interpretation.png
  content/data-science-projects/categorical-encoding/results.png
  content/data-science-projects/categorical-encoding/rulepath.png
  content/getting-started/basic-tutorial/index.md
  content/getting-started/basic-tutorial/new-notebook.png
  content/getting-started/basic-tutorial/new-terminal.png
  content/getting-started/basic-tutorial/routes.png
  content/getting-started/hello-world.ipynb
  content/getting-started/index.md
  content/getting-started/jupyter-notebooks/index.mdx
  content/getting-started/jupyter-notebooks/notebook.ipynb
  content/toc.yaml
Labels: do-not-merge/needs-rebase, size/XL

#81 add the ADR as remote content
  .gitignore
  content-sources.yaml
  content/blueprint-toc.yaml
  toc-sources.yaml
Labels: approved, size/M

#82 script to clean local dev env
  Makefile
  README.md
  scripts/dev-clean.sh
Labels: size/S

#64 Workaround for podman s2i builds
  scripts/build.sh
Labels: approved, size/S

#85 let oindrilla approve
  OWNERS
Labels: size/XS

#84 Projects Overview in Data Science Projects
  content/data-science-projects/projects-overview/index.md
  content/toc.yaml
Labels: approved, size/XS

#83 text align in navigation buttons left
  src/components/Layout/Layout.scss
Labels: approved, size/XS

#80 add CICD remote content
  .gitignore
  content-sources.yaml
  toc-sources.yaml
Labels: approved, size/XS

#91 Adds notebook content from ocp-ci project
  content-sources.yaml
  content/aici-toc.yaml
  content/toc.yaml
  toc-sources.yaml
Labels: approved, size/S

#89 fixed blueprint repo urls
  content-sources.yaml
  content/blueprint-toc.yaml
Labels: size/XS

#92 Updates README instructions for including remote notebooks
  README.md
Labels: approved, size/S

#103 Added contribute page
  content/contribute-toc.yaml
  content/contribute/index.md
  toc-sources.yaml
Labels: size/S

#99 remove redirect of index page and link logo to /
  content/index.md
  content/toc.yaml
  gatsby-node.js
  src/components/Layout/Header.js
Labels: approved, size/S

#104 rename domain
  README.md
  gatsby-config.js
Labels: approved, size/XS

#53 Add continuous deployment docs
  content-sources.yaml
  content/cd-toc.yaml
Labels: approved, size/M

#109 Ignore index.md file from cd repo
  content-sources.yaml
Labels: approved, size/XS

#113 Add Cloud Price Analysis to Projects Overview
  content/data-science-projects/projects-overview/index.md
Labels: approved, size/S

#112 added failure type classification with testgrid data project doc to "AI for Continuous integration"
  content/aici-toc.yaml
Labels: approved, size/XS

#115 Cleanup local content
  content/aici-toc.yaml
  content/blueprint-toc.yaml
  content/cd-toc.yaml
  content/contribute-toc.yaml
  content/contribute/index.md
  content/data-science-projects/hello-world.ipynb
  content/dsw-toc.yaml
  content/getting-started/index.md
  content/moc-toc.yaml
  content/resources/index.md
  content/toc.yaml
  toc-sources.yaml
Labels: approved, size/L

#117 Top Navigation
  content-sources.yaml
  content/blueprints.yaml
  content/blueprints/index.md
  content/data-science-projects/categorical-encoding/approach.png
  content/data-science-projects/categorical-encoding/dataset.png
  content/data-science-projects/categorical-encoding/index.md
  content/data-science-projects/categorical-encoding/interpretation.png
  content/data-science-projects/categorical-encoding/results.png
  content/data-science-projects/categorical-encoding/rulepath.png
  content/data-science.yaml
  content/data-science/hello-world.ipynb
  content/data-science/index.md
  content/getting-started/index.md
  content/index.md
  content/operators.yaml
  content/operators/index.md
  content/toc.yaml
  content/users.yaml
  content/users/index.md
  gatsby-node.js
  src/components/Layout/Header.js
  src/components/Layout/Layout.js
  src/components/Layout/NavSidebar.js
  toc-sources.yaml
Labels: approved, size/XL

#120 Ignore files that break build
  content-sources.yaml
Labels: approved, size/XS

#121 replace custom git clone logic with gatsby plugin
  content-sources.yaml
  gatsby-config.js
  gatsby-node.js
  package-lock.json
  package.json
Labels: approved, size/L

#118 Update Readme instructions
  README.md
Labels: size/L

#123 Converting all remote repos to use gatsby-source-git
  .gitignore
  README.md
  clone-remote-content-sync.js
  clone-remote-content.js
  content-sources.yaml
  content/data-science.yaml
  content/operators.yaml
  content/users.yaml
  gatsby-config.js
  gatsby-node.js
  package.json
  src/templates/JupyterNotebook.js
  src/templates/JupyterNotebook.scss
Labels: approved, size/L

#124 update README
  README.md
  content/examples/jupyter_notebook.ipynb
  content/examples/markdown.md
  content/examples/mdx.mdx
  package.json
  scripts/dev.sh
  src/templates/Doc.js
Labels: approved, size/L

#126 Dont show burger toggle on main page
  src/components/Layout/Header.js
Labels: approved, size/XS

#127 fix(gatsby-source-git): Fix including of images
  gatsby-config.js
Labels: approved, size/S

#128 update landing page
  content/index.md
Labels: approved, size/L

#129 fix(remote-content): Remove MDX exceptions
  content/operators.yaml
  gatsby-config.js
Labels: approved, size/S

#131 move config files to /config dir
  README.md
  config-utils.js
  config/blueprints.yaml
  config/content-sources.yaml
  config/data-science.yaml
  config/operators.yaml
  config/toc-sources.yaml
  config/users.yaml
  gatsby-node.js
Labels: approved, size/S

#133 Keep extension for .md and .ipynb files in links
  README.md
  config/blueprints.yaml
  config/data-science.yaml
  config/operators.yaml
  config/users.yaml
  content/index.md
  gatsby-config.js
  gatsby-node.js
  package-lock.json
  package.json
Labels: size/L

#132 autogenerate ids for navigation
  README.md
  config/blueprints.yaml
  config/data-science.yaml
  config/operators.yaml
  config/users.yaml
  gatsby-node.js
  package-lock.json
  package.json
Labels: size/L

#134 fix(gatsby): Fix image louder blur on images with alpha
  gatsby-config.js
Labels: approved, size/XS

#135 add tumido to approvers
  OWNERS
Labels: approved, size/XS

#136 modification of href for failure-type-classification-with-the-testgrid-data-project-doc
  config/data-science.yaml
Labels: approved, size/XS
