Repository operate-first/operate-first.github.io-old, pull requests merged in 2020-10, with the labels that each got.

#34 linked community manifesto
  content/resources/index.md
  content/toc.yaml
Labels: size/S

#35 Clone remote content from git repos.
  .gitignore
  README.md
  clone-remote-content-sync.js
  clone-remote-content.js
  config-utils.js
  content-sources.yaml
  content/cd-toc.yaml
  content/resources/index.md
  content_config.yaml
  gatsby-node.js
  package-lock.json
  package.json
  scripts/build.sh
  scripts/dev.sh
  src/components/Layout/NavSidebar.js
  toc-sources.yaml
Labels: size/XL

#44 Updated readme with steps to add remote repo
  README.md
Labels: size/M

#46 Add default patternfly class to table.
  gatsby-config.js
Labels: size/XS

#49 enable aicoe-ci to assist with builds
  .aicoe-ci.yaml
Labels: size/XS

#47 added configuration file analysis blog
  .gitignore
  content-sources.yaml
  content/toc.yaml
Labels: size/S

#51 Move docs for publish into sub-directory
  README.md
  content-sources.yaml
Labels: size/S

#54 Update README
  README.md
Labels: size/XS

#41 Projects Overview
  content/projects-overview/index.md
  content/toc.yaml
Labels: size/M

#56 Adds "AI for CI" initial project doc to operate first website
  .gitignore
  content-sources.yaml
  content/toc.yaml
Labels: size/S

#60 [WIP] Update the basic tutorial page
  content/getting-started/basic-tutorial/index.md
Labels: do-not-merge/work-in-progress, size/XS
