Repository operate-first/operate-first.github.io-old, pull requests merged in 2021-02, with the labels that each got.

#194 Add SRE documentation
  config/operators.yaml
  gatsby-config.js
Labels: approved, lgtm, size/S

#195 article on how to open source cloude operations
  content/how-to-open-source-cloud-operations.md
  content/index.md
Labels: approved, size/M

#196 fix links for mailing list notebook pages
  config/data-science.yaml
Labels: approved, size/XS

#198 Add content to the blueprints page.
  content/blueprints/index.md
Labels: approved, size/S

#197 Add config for kubeflow access docs
  config/users.yaml
Labels: approved, lgtm, size/XS

#199 added info to section headers and redirect
  content/operators/index.md
  content/users/index.md
  gatsby-config.js
  package-lock.json
  package.json
Labels: approved, lgtm, size/XXL

#200 Fix link
  content/how-to-open-source-cloud-operations.md
Labels: approved, size/XS

#203 added link to additional resources
  config/blueprints.yaml
  content/blueprints/additional-resources.md
  content/blueprints/index.md
Labels: approved, size/S

#201 added website footer and ref to logo
  src/components/Layout/Footer.js
  src/components/Layout/Footer.scss
  src/components/Layout/Layout.js
  src/components/Layout/RHLogo.png
  src/components/Layout/index.js
Labels: approved, size/L

#204 Add market research doc to "AI for Continuous Integration" section
  config/data-science.yaml
Labels: approved, size/XS

#205 Add Elyra tutorial.
  config/users.yaml
  gatsby-config.js
Labels: approved, lgtm, size/S
