Repository operate-first/operate-first.github.io-old, pull requests merged in 2021-11, with the labels that each got.

#315 create community tab + pages
  README.md
  config/community.yaml
  config/toc-sources.yaml
  content/community/index.md
  gatsby-config.js
  src/components/Layout/Header.js
Labels: approved, size/S, lgtm

#316 feat: Add twitter icon
  gatsby-config.js
  src/components/Layout/Header.js
Labels: approved, size/XS, lgtm

#321 Adding github-labeler to gastby-config.js
  gatsby-config.js
Labels: approved, size/XS, lgtm

#320 adding github-labeler project
  content/data-science/projectsoverview.md
Labels: size/S, lgtm

#322 Fix broken links and restructure for hitchikers page.
  config/hitchhikers-guide.yaml
  config/toc-sources.yaml
  config/users.yaml
  content/community/index.md
  content/hitchhikers-guide/alerts.md
  content/hitchhikers-guide/argocd_access.md
  content/hitchhikers-guide/index.md
  content/hitchhikers-guide/moc_cluster_access.md
  content/hitchhikers-guide/operations-intro.md
  content/index.md
  content/users/index.md
  gatsby-config.js
  src/components/Layout/Header.js
Labels: approved, size/L, lgtm

#323 Add Operate First Data Science Community to website
  config/data-science.yaml
  gatsby-config.js
Labels: size/S, lgtm

#325 Update gatsby-config.js
  gatsby-config.js
Labels: approved, size/XS, lgtm

#324 adding my project to the side bar
  config/data-science.yaml
Labels: size/S, lgtm

#330 Fix a broken link to the AI4CI page
  content/data-science/projectsoverview.md
Labels: size/XS, lgtm

#332 re-arrange data science config
  config/data-science.yaml
Labels: approved, size/M, lgtm

#333 feat: Add GitHub actions for deploying website
  .github/workflows/build_job.yaml
  .travis.yml
  package.json
Labels: size/M, lgtm

#334 feat: Add manual and cron based trigger to website build action
  .github/workflows/build_job.yaml
Labels: size/M, lgtm

#335 docs: Add Github Actions CI mention to readme
  README.md
  misc/manual_ci_trigger.png
Labels: size/XS, lgtm

#328 feat: Add meteor to the website
  config/data-science.yaml
  gatsby-config.js
Labels: approved, size/XS, lgtm
