Repository operate-first/operate-first.github.io-old, pull requests merged in 2021-04, with the labels that each got.

#226 Add guidelines-for-reviewing-datascience-code.md to Operate first
  config/data-science.yaml
Labels: approved, size/XS

#228 added projects to project list
  content/data-science/index.md
Labels: approved, lgtm, size/M

#229 Add basic Thanos access docs
  config/users.yaml
Labels: approved, size/XS

#230 Add redirect from /telemetry to the OpenInfralabs page
  content/telemetry/index.md
Labels: approved, lgtm, size/XS

#225 `pet-image-detection` added to data science section
  config/data-science.yaml
  gatsby-config.js
Labels: approved, lgtm, size/S

#233 added elyra workflow doc
  config/data-science.yaml
Labels: approved, lgtm, size/XS

#234 Add config for Prometheus docs
  config/users.yaml
Labels: approved, size/XS

#236 Add jupyterhub runbook to users tab
  config/users.yaml
  gatsby-config.js
Labels: approved, lgtm, size/S

#238 Update invalid links, and update outdated info.
  README.md
  config/operations.yaml
  config/operators.yaml
  config/toc-sources.yaml
  config/users.yaml
  content/operations/alerts.md
  content/operations/index.md
  content/operators/index.md
  content/users/argocd_access.md
  content/users/moc_cluster_access.md
  gatsby-config.js
  src/components/Layout/Header.js
Labels: approved, lgtm, size/L

#235 Index page updates
  content/index.md
  src/components/Layout/Layout.js
  src/components/Layout/Layout.scss
  src/templates/Markdown.js
Labels: approved, size/L

#240 fix: Apply text centering only to the front page
  content/index.md
  src/templates/Markdown.js
Labels: approved, size/XS

#241 fix: Padding for all sites except frontpage
  content/index.md
  src/templates/Markdown.js
Labels: approved, lgtm, size/XS

#242 Add emphasis on "working in the open"
  content/index.md
Labels: approved, lgtm, size/XS
