Repository operate-first/operate-first.github.io-old, pull requests merged in 2021-09, with the labels that each got.

#308 Adding new lists, small lang tweaks
  content/index.md
Labels: size/XS

#301 Add argocd console link to argocd section.
  content/users/argocd_access.md
Labels: approved, size/XS, lgtm

#309 New landing page for DS section
  config/data-science.yaml
  content/data-science/index.md
  content/data-science/projectsoverview.md
Labels: approved, size/L, lgtm
