Repository operate-first/operate-first.github.io-old, pull requests merged in 2021-12, with the labels that each got.

#336 Switch hitchiker with handbook, and add remote link support.
  .pre-commit-config.yaml
  OWNERS
  config/community-handbook.yaml
  config/community.yaml
  config/hitchhikers-guide.yaml
  config/toc-sources.yaml
  content/community-handbook/alerts.md
  content/community-handbook/argocd_access.md
  content/community-handbook/index.md
  content/community-handbook/moc_cluster_access.md
  content/community-handbook/operations-intro.md
  gatsby-config.js
  src/components/Layout/Header.js
  src/components/Layout/NavSidebar.js
Labels: do-not-merge/hold, size/L, lgtm

#338 Sending CTA links to new landing pages
  content/index.md
  content/open-source-developers/index.md
  content/sre-learners/index.md
Labels: size/M, lgtm

#340 updated data science workflow tabs
  config/data-science.yaml
Labels: size/XS, lgtm
