Repository operate-first/operate-first.github.io-old, pull requests merged in 2021-01, with the labels that each got.

#160 Add time series pages
  config/data-science.yaml
  gatsby-config.js
Labels: approved, size/S

#168 Add argocd onboard and application adding docs
  config/users.yaml
  gatsby-config.js
Labels: size/S

#166 Add hard drive failure prediction blog
  config/data-science.yaml
  gatsby-config.js
Labels: approved, size/S

#172 Fix build error for #166
  gatsby-config.js
Labels: approved, size/XS

#169 embed youtube videos
  README.md
  content/examples/markdown.md
  gatsby-config.js
  package-lock.json
  package.json
Labels: approved, size/M

#173 upgrade all packages
  package-lock.json
  package.json
Labels: approved, size/XXL

#185 Add operate-first/apps as document sources
  config/users.yaml
  gatsby-config.js
Labels: approved, size/S

#175 feat: Add Mailing list analysis initial content
  config/data-science.yaml
  content/data-science/index.md
  gatsby-config.js
Labels: approved, size/M

#186 update rel link to document
  config/data-science.yaml
Labels: approved, size/XS

#188 Add a simple website status badge
  README.md
Labels: approved, size/S

#189 feat: Add onboarding docs and update ADRs
  config/blueprints.yaml
  config/operators.yaml
  config/users.yaml
  gatsby-config.js
Labels: approved, size/M

#190 fix: Set correct heading for Ceph provisioning guide
  config/operators.yaml
Labels: approved, size/XS

#192 Add project materials for OpenShift Anomaly Detection
  config/data-science.yaml
  content/data-science/index.md
  gatsby-config.js
Labels: approved, size/S
