Repository operate-first/operate-first.github.io-old, pull requests merged in 2021-06, with the labels that each got.

#257 removed quotes around Operate First on main page
  content/index.md
Labels: approved, lgtm, size/XS

#258 feat: Add issuing certificates to general FAQ
  config/users.yaml
Labels: approved, lgtm, size/XS

#263 Change the name for Data Science code review doc
  config/data-science.yaml
Labels: approved, lgtm, size/XS

#264 chore: Add new owners
  OWNERS
Labels: approved, lgtm

#261 Edits/addition to Operations page
  content/operations/index.md
Labels: approved, lgtm, size/S
