Repository operate-first/operate-first.github.io-old, pull requests merged in 2021-08, with the labels that each got.

#281 reorganized data science section
  config/data-science.yaml
  content/data-science/index.md
Labels: approved, size/L, lgtm

#283 feat: Make dev enviroment possible from toolbox
  Makefile
Labels: approved, lgtm

#279 Add documentation to Pulp instance
  config/users.yaml
  gatsby-config.js
Labels: approved, size/S, lgtm

#284 Added data skipping section to data-science
  config/data-science.yaml
  gatsby-config.js
Labels: approved, size/S, lgtm

#282 Re-design of the home page
  config/operations.yaml
  content/index.md
  content/logo.png
  gatsby-config.js
  src/components/Layout/Layout.scss
Labels: approved, size/L, lgtm

#286 refactor: Use eslint, prettier, precommit for linting, refactor some components to proper React
  .pre-commit-config.yaml
  .prettierrc
  .prow.yaml
  .s2i/environment
  .travis.yml
  config-utils.js
  config/blueprints.yaml
  config/content-sources.yaml
  config/operations.yaml
  config/toc-sources.yaml
  content/blueprints/additional-resources.md
  content/blueprints/index.md
  content/data-science/index.md
  content/examples/jupyter_notebook.ipynb
  content/examples/markdown.md
  content/examples/mdx.mdx
  content/how-to-open-source-cloud-operations.md
  content/index.md
  content/operations/index.md
  content/telemetry/index.md
  content/users/index.md
  gatsby-browser.js
  gatsby-config.js
  gatsby-node.js
  misc/how-to-livestream-meeting.md
  package-lock.json
  package.json
  scripts/gh-pages.sh
  scripts/templates/base/deployment.yaml
  src/components/JupyterNotebook/JupyterNotebook.js
  src/components/JupyterNotebook/JupyterNotebook.scss
  src/components/JupyterNotebook/index.js
  src/components/Layout/Footer.js
  src/components/Layout/Footer.scss
  src/components/Layout/Header.js
  src/components/Layout/Launcher.js
  src/components/Layout/Layout.js
  src/components/Layout/NavSidebar.js
  src/components/Layout/Samples.js
  src/components/Layout/index.js
  src/components/seo.js
  src/pages/404.js
  src/pages/using-typescript.tsx
  src/templates/Doc.js
  src/templates/JupyterNotebook.js
  src/templates/JupyterNotebook.scss
  src/templates/Markdown.js
  yamllint-config.yaml
Labels: approved, size/XXL, lgtm

#292 fix: NavSidebar invert filter
  src/components/Layout/NavSidebar.js
Labels: approved, size/XS, lgtm

#293 fix: Push footer to bottop of a page
  src/components/Layout/Layout.js
Labels: approved, size/XS, lgtm

#288 feat: Display a banner from frontmatter
  content/index.md
  gatsby-config.js
  gatsby-node.js
  package-lock.json
  package.json
  src/components/Layout/Layout.js
  src/components/Layout/Layout.scss
  src/templates/Markdown.js
Labels: approved, size/L, lgtm

#295 fix: NavSidebar filter pages properly
  src/components/Layout/NavSidebar.js
Labels: approved, size/S, lgtm

#287 Update Description to remove references to ODH
  content/index.md
Labels: approved, size/XS, lgtm

#290 Canonical URL for our CoC
  content/code_of_conduct/index.md
Labels: approved, size/XS, lgtm

#306 updated prow resource limits
  .prow.yaml
Labels: approved, size/XS, lgtm
