Repository operate-first/operate-first.github.io-old, pull requests merged in 2022-01, with the labels that each got.

#341 chore: Force different actor on deploy workflow schedule trigger
  .github/workflows/build_job.yaml
Labels: size/S, lgtm

#342 chore: Fix github action syntax
  .github/workflows/build_job.yaml
Labels: size/XS

#345 added README.md to urls to fix url breaks
  config/data-science.yaml
  gatsby-config.js
Labels: size/S

#346 updated url to ds learning path
  content/index.md
Labels: size/XS, lgtm

#347 Updated OpenShift broken link on project README
  README.md
Labels: do-not-merge/hold, size/XS, lgtm

#348 enable ipynb format for ds-workflows repo
  gatsby-config.js
Labels: size/XS
