Repository operate-first/operate-first.github.io-old, pull requests merged in 2022-02, with the labels that each got.

#352 Clean up community page
  content/community/index.md
Labels: size/M, lgtm

#355 Fix broken link to community handbook
  content/index.md
Labels: size/XS, lgtm

#360 Removal of Zero Cluster from cluster drop down
  gatsby-config.js
Labels: size/XS, lgtm

#362 Replaced broken emoji shortcode
  content/data-science/index.md
Labels: size/XS, lgtm

#363 Better looking 404
  src/pages/404.js
Labels: size/S
